name: ppde642

channels:
  - conda-forge
  - pytorch

dependencies:
  - beautifulsoup4
  - cartopy
  - cenpy
  - contextily
  - folium
  - geopandas
  - jupyterlab
  - mapclassify
  - osmnx=1.8.1
  - pandana
  - pandas
  - pre-commit
  - pysal
  - python=3.11.*
  - rasterio
  - seaborn
  - scikit-learn
  - scipy
  - statsmodels

  # computer vision and NLP
  - gensim
  - nltk
  - pillow
  - pytorch
  - torchvision

  # others (unused)
  # bokeh
  # datashader
  # holoviews
  # keras
  # psycopg2
  # pydeck
  # urbanaccess
