name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    defaults:
      run:
        shell: bash -elo pipefail {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Create environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          cache-downloads: true
          cache-environment: true
          environment-file: environment.yml
          post-cleanup: none

      - name: Test environment
        run: |
          python -m ipykernel install --sys-prefix --name ppde642 --display-name "Python (ppde642)"
          jupyter kernelspec list
          ipython -c "import osmnx; print('OSMnx version', osmnx.__version__)"
          ipython -c "from nltk.corpus import brown; print(brown.words())"

      - name: Lint
        run: |
          SKIP=no-commit-to-branch pre-commit run --all-files
